# Generated by Django 2.0 on 2019-03-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAllocation', models.DateTimeField()),
                ('taskToBePerformedBy', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='allocate',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Task'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Worker'),
        ),
    ]
