# Generated by Django 2.0 on 2019-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190423_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurfaceTension',
        ),
    ]
