# Generated by Django 2.0 on 2019-04-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0003_delete_surfacetension'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidSurfaceTension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfaceTension', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolidEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceTension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.IntegerField()),
                ('liquid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.LiquidSurfaceTension')),
                ('solid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.SolidEnergy')),
            ],
        ),
    ]
