# Generated by Django 2.0 on 2019-04-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_liquidsurfacetension_solidenergy_surfacetension'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='surfacetension',
            name='liquid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.LiquidEnergy'),
        ),
        migrations.DeleteModel(
            name='LiquidSurfaceTension',
        ),
    ]
